// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Preferences { recent_searches: Array<string>, show_file_extensions: boolean, }